### ISSUE TITLE
Question on ee part of ewaldsum

### ISSUE THREAD

**Issue by mavenlin** [bytedance/DeepSolid#1]
Thank you for making this code open-source.

One question comes to me when I read the [ewaldsum](https://github.com/bytedance/DeepSolid/blob/master/DeepSolid/ewaldsum.py#L156). When the electron distances are calculated the same way as the ion distances, does it imply that the electrons are sampled from one cell and mirrored periodically instead of sampled independently from each supercell? Would there be a problem doing so?

**Comment by GiantElephant123** [comment]
Thanks for asking and sorry for the late response. You are right, electrons outside the chosen supercell are mirror placed. This is called supercell approximation in physics and it's employed because we can't treat all the electrons in solids (order ~ 10^23). And due to this approximation, our calculation will only make sense and reach the thermodynamic limit if we choose a large enough supercell (or a fine k-point mesh in SCF language).

**Comment by mavenlin** [comment]
It is a very prompt response! Thanks for clarifying.
